// Generated by CoffeeScript 1.3.3
(function() {
  var processElevationPixel;

  processElevationPixel = function(brightness) {
    if (brightness < 100) {
      return {
        r: 0,
        g: 0,
        b: brightness
      };
    } else if (brightness < 300) {
      return {
        r: 0,
        g: brightness,
        b: 0
      };
    } else if (brightness <= 255 / ratios.elevation) {
      return {
        r: brightness,
        g: brightness,
        b: brightness
      };
    } else {
      return {
        r: 255,
        g: 255,
        b: 255
      };
    }
  };

  window.DFHMPreview = {
    renderElevation: function(data, width, height) {
      var b, canvas, ctx, g, i, imageData, length, r, srcLength, target, targetCanvas, targetHeight, targetWidth, _i, _ref;
      canvas = $('<canvas/>')[0];
      canvas.width = width;
      canvas.height = height;
      ctx = canvas.getContext('2d');
      ctx.clearRect(0, 0, width, height);
      imageData = ctx.getImageData(0, 0, width, height);
      srcLength = data.length;
      length = imageData.data.length;
      for (i = _i = 0; 0 <= srcLength ? _i < srcLength : _i > srcLength; i = 0 <= srcLength ? ++_i : --_i) {
        target = i * 4;
        _ref = processElevationPixel(data[i]), r = _ref.r, g = _ref.g, b = _ref.b;
        imageData.data[target] = r;
        imageData.data[target + 1] = g;
        imageData.data[target + 2] = b;
        imageData.data[target + 3] = 255;
      }
      targetCanvas = $('#preview')[0];
      targetWidth = targetCanvas.width;
      targetHeight = targetCanvas.height;
      ctx = targetCanvas.getContext('2d');
      ctx.clearRect(0, 0, targetWidth, targetHeight);
      return ctx.putImageData(imageData, 0, 0, targetWidth, targetHeight);
    },
    renderOther: function(data, elevation) {}
  };

}).call(this);
