// Generated by CoffeeScript 1.3.3
(function() {
  var pixelToGreyscale;

  pixelToGreyscale = function(r, g, b) {
    return (r * 0.299) + (g * 0.587) + (b * 0.114);
  };

  window.DFHMImport = {
    toGreyscale: function(ctx) {
      var i, imageData, length, _fn, _i;
      imageData = ctx.getImageData(0, 0, 17, 17);
      length = imageData.data.length;
      _fn = function(i) {
        var brightness;
        brightness = pixelToGreyscale(imageData.data[i], imageData.data[i + 1], imageData.data[i + 2]);
        imageData.data[i] = imageData.data[i + 1] = imageData.data[i + 2] = brightness;
        return imageData.data[i + 3] = 255;
      };
      for (i = _i = 0; _i <= length; i = _i += 4) {
        _fn(i);
      }
      return ctx.putImageData(imageData, 0, 0);
    }
  };

}).call(this);
