// Generated by CoffeeScript 1.3.3
(function() {
  var pixelToGreyscale;

  pixelToGreyscale = function(r, g, b) {
    return (r * 0.299) + (g * 0.587) + (b * 0.114);
  };

  window.DFHMImport = {
    toHeightValue: function(image, width, height, type) {
      var canvas, ctx, i, imageData, length, logged, offset, ratio, _i, _results;
      canvas = $('<canvas/>')[0];
      canvas.width = width;
      canvas.height = height;
      ctx = canvas.getContext('2d');
      ctx.clearRect(0, 0, width, height);
      ctx.drawImage(image, 0, 0, width, height);
      imageData = ctx.getImageData(0, 0, width, height);
      length = imageData.data.length;
      ratio = window.ratios[type];
      offset = window.offsets[type];
      logged = false;
      _results = [];
      for (i = _i = 0; _i < length; i = _i += 4) {
        _results.push(((pixelToGreyscale(imageData.data[i], imageData.data[i + 1], imageData.data[i + 2])) * ratio) + offset);
      }
      return _results;
    }
  };

}).call(this);
