// Generated by CoffeeScript 1.3.3
(function() {
  var pixelToGreyscale;

  pixelToGreyscale = function(r, g, b) {
    return (r * 0.299) + (g * 0.587) + (b * 0.114);
  };

  window.DFHMImport = {
    toHeightValue: function(image, width, height, type, ratioOverride, offsetOverride) {
      var canvas, ctx, i, imageData, length, offset, overrideValue, ratio, _i, _results;
      if (ratioOverride == null) {
        ratioOverride = false;
      }
      if (offsetOverride == null) {
        offsetOverride = false;
      }
      canvas = $('<canvas/>')[0];
      canvas.width = width;
      canvas.height = height;
      ctx = canvas.getContext('2d');
      ctx.clearRect(0, 0, width, height);
      ctx.drawImage(image, 0, 0, width, height);
      imageData = ctx.getImageData(0, 0, width, height);
      length = imageData.data.length;
      ratio = window.ratios[type];
      if (ratioOverride !== false) {
        overrideValue = parseInt(ratioOverride, 10);
        if (overrideValue !== NaN) {
          ratio += overrideValue;
        }
      }
      offset = window.offsets[type];
      if (offsetOverride !== false) {
        overrideValue = parseInt(offsetOverride, 10);
        if (overrideValue !== NaN) {
          offset += overrideValue;
        }
      }
      _results = [];
      for (i = _i = 0; _i < length; i = _i += 4) {
        _results.push(((pixelToGreyscale(imageData.data[i], imageData.data[i + 1], imageData.data[i + 2])) * ratio) + offset);
      }
      return _results;
    }
  };

}).call(this);
