// Generated by CoffeeScript 1.3.3
(function() {
  var $, canvas, ctx, init, onFileSelected, onImageLoaded;

  $ = jQuery;

  canvas = null;

  ctx = null;

  onImageLoaded = function(event) {
    var dummyImage;
    dummyImage = new Image();
    dummyImage.onload = function() {
      ctx.clearRect(0, 0, 300, 300);
      return ctx.drawImage(dummyImage, 0, 0, 300, 300);
    };
    return dummyImage.src = event.target.result;
  };

  onFileSelected = function(event) {
    var file, reader;
    if (event.target.files[0]) {
      file = event.target.files[0];
      if (file.type.match("image.*")) {
        reader = new FileReader();
        reader.onload = onImageLoaded;
        return reader.readAsDataURL(file);
      } else {
        return alert("Not an image");
      }
    }
  };

  init = function() {
    if (window.File && window.FileReader) {
      $('#test-loader').change(onFileSelected);
      canvas = $('#output')[0];
      return ctx = canvas.getContext('2d');
    } else {
      return alert("noes");
    }
  };

  $(document).ready(init);

}).call(this);
